version: "3.7"

services:
    backend:
        image: telebot:latest # or image api
        container_name: telebot
        env_file:
            - .env
        command: python src/main.py
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "200M"
                max-file: "5"

# docker-compose -f "docker-compose.yml" up -d --build